#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d firefox terminal 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.58
#bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true

#Colors
bspc config normal_border_color		"#d65d0e"
bspc config active_border_color		"#fe8019"
bspc config focused_border_color	"#fe8019"
bspc config presel_feedback_color	"#fabd2f"

# Start Polybar
$HOME/.config/polybar/launch.sh

# for java applications
wmname LG3D

# Start my script
$HOME/.config/bspwm/floating_rule.sh
